# Data args
n_trials: 5000 # num trials total to generate
split_fracs: [0.8, 0.1, 0.1] # train/val/test split

# Training args
batch_size: 1000
lr: 0.01
epochs: 1000
reg: 0.1

# Model args
no_target_hidden: 100
no_target_num_layers: 10
dropout: 0.0
graph_enc_hidden: 100
graph_enc_out: 10
graph_enc_num_layers: 10
target_hidden: 100
target_num_layers: 10
num_heads: 4 # only for GAT
concat: False # only for GAT