# Target sampler
num_targets_range: [3,10]
speed_range: [2,5]
goal_range: [200, 500]
offset_range: [300, 800]
size_range: [20,100]
n_disc: 10
min_allowed: 100

# Endpoint sampler
start_bounds: [0,0,1000,1000] # Range for where to place start relative to costmap center
goal_dist_range: [1000,1500] # Range for how far away to place start from goal
min_goal_allowed: 200 # Min distance to static obstacle for generated start/goal

# Wind sampler
wind_speed_range: [8,28]
wind_yaw_range: [0, 6.28318530718]
